### ISSUE TITLE
Password set at every reboot

### ISSUE THREAD

**Issue by iooner** [kerberos-io/kios#19] opened 2017-07-31 19:17 UTC
Hi!
At every reboot, Kios ask to set the password.

**Comment by cedricve** [comment] 2017-07-31 19:17
Not sure what you mean, can you supply a screenshot?

**Comment by badams** [comment] 2017-08-13 09:43
Ran into this too.

I unplugged my RPi  and plugged back in, but when I tried to log into Kerberos i was asked to create a user account again.

This seems to be caused by [this line](https://github.com/kerberos-io/web/blob/283f053a8e975f18279b2608478347ee4ad029d9/routes/web.php#L26)

My understanding is that when the app is restarted the config values are just read from [this file](https://github.com/kerberos-io/web/blob/master/config/kerberos.php#L4) which leads to the account setup page.

**Comment by cedricve** [comment] 2017-08-13 10:47
thanks for reporting @badams, well the config should be updated when finishing the welcome page.
https://github.com/kerberos-io/web/blob/283f053a8e975f18279b2608478347ee4ad029d9/app/Http/Controllers/UserController.php#L38-L58

Not sure what is going wrong there.

**Comment by cedricve** [comment] 2017-08-13 13:13
@badams just tried it myself using v2.4.1 but couldn't reproduce. Can you try it again with a fresh install?

**Comment by cedricve** [comment] 2017-11-01 14:40
Will be fixed in next release.

**Comment by cedricve** [comment] 2017-11-16 10:20
fixed in KiOS v2.5.0

**Closed as completed by cedricve** 2017-11-16 10:20 UTC
